# Generated by Django 3.0.1 on 2020-01-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=200)),
                ('date', models.DateField(help_text='Date when the project was started')),
                ('access_code', models.CharField(blank=True, help_text='Code for accessing the project. This prevents spamming', max_length=6)),
                ('subject', models.ForeignKey(help_text='The subject of the project ', on_delete=django.db.models.deletion.CASCADE, to='groupprojects.Subject')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
