# Generated by Django 3.0.1 on 2020-01-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
