# Generated by Django 3.0.1 on 2020-01-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0003_auto_20200104_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='completed_status',
            new_name='is_completed',
        ),
    ]
