# Generated by Django 3.0.1 on 2020-01-04 14:46

from django.db import migrations, models

from django.template.defaultfilters import slugify

def update_slug(apps, schema_editor):
    Project = apps.get_model('groupprojects', 'Project')

    for instance in Project.objects.all():
        if not instance.slug:
            instance.slug = slugify(instance.name)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0004_auto_20200104_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),

        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop)
    ]


