# Generated by Django 3.0.1 on 2020-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0006_auto_20200104_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
