# Generated by Django 3.0.1 on 2020-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0007_auto_20200104_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
