# Generated by Django 3.0.1 on 2020-01-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0008_auto_20200104_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'slug')},
        ),
    ]
