# Generated by Django 3.0.1 on 2020-01-12 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupprojects', '0009_auto_20200104_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField(help_text='The proposal of the User for joining a project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupprojects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='groupprojects.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
