# Generated by Django 3.0.1 on 2020-01-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupprojects', '0012_auto_20200112_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, help_text="What the Project is all about or the details about the characteristics of the student you're going to recruit, etc."),
        ),
    ]
